import { useState } from "react";
import { CodeBlockIcon, CopyIcon, CheckIcon, DownloadIcon } from "@phosphor-icons/react";
import { ComprehensiveTableDetails } from "../types";
import { cn } from "@/lib/utils";
import CodeMirror from "@uiw/react-codemirror";
import { sql, PostgreSQL } from "@codemirror/lang-sql";
import { tokyoNight } from "@uiw/codemirror-theme-tokyo-night";

export default function SqlViewerSection({ details }: { details: ComprehensiveTableDetails }) {
  const [activeTab, setActiveTab] = useState("DDL");
  const [copied, setCopied] = useState(false);

  const generateCreateTable = () => {
    let sql = `CREATE TABLE ${details.summary.schema}.${details.summary.table_name} (\n`;

    // Columns
    const colLines = details.columns.map(c => {
      let line = `  ${c.name} ${c.data_type}`;
      if (!c.nullable) line += " NOT NULL";
      if (c.default_value) line += ` DEFAULT ${c.default_value}`;
      if (c.is_identity) line += " GENERATED BY DEFAULT AS IDENTITY";
      if (c.collation) line += ` COLLATE ${c.collation}`;
      return line;
    });

    sql += colLines.join(",\n");

    // Primary keys
    const pkConstraint = details.constraints.find(c => c.type_ === "p");
    if (pkConstraint && pkConstraint.columns && pkConstraint.columns.length > 0) {
      sql += `,\n  PRIMARY KEY (${pkConstraint.columns.join(", ")})`;
    }

    sql += "\n);";
    return sql;
  };

  const generateIndexes = () => {
    if (!details.indexes || details.indexes.length === 0) return "-- No indexes";
    return details.indexes.map(idx => idx.definition).join(";\n\n") + ";";
  };

  const generateConstraints = () => {
    if (!details.constraints || details.constraints.length === 0) return "-- No constraints";
    return details.constraints.map(c => `-- ${c.name}\nALTER TABLE ${details.summary.schema}.${details.summary.table_name} ADD CONSTRAINT ${c.name} ${c.definition};`).join("\n\n");
  };

  const generateTriggers = () => {
    if (!details.triggers || details.triggers.length === 0) return "-- No triggers";
    return details.triggers.map(trg => trg.definition).join(";\n\n") + ";";
  };

  const generatePolicies = () => {
    if (!details.rls || !details.rls.policies || details.rls.policies.length === 0) return "-- No RLS policies";
    return details.rls.policies.map(pol => {
      let sql = `CREATE POLICY ${pol.name} ON ${details.summary.schema}.${details.summary.table_name}`;
      if (pol.command) sql += ` FOR ${pol.command}`;
      if (pol.roles && pol.roles.length > 0) sql += ` TO ${pol.roles.join(", ")}`;
      if (pol.using_expression) sql += `\n  USING (${pol.using_expression})`;
      if (pol.with_check_expression) sql += `\n  WITH CHECK (${pol.with_check_expression})`;
      return sql + ";";
    }).join("\n\n");
  };

  const generateComments = () => {
    let sql = [];
    if (details.table_comment) {
      sql.push(`COMMENT ON TABLE ${details.summary.schema}.${details.summary.table_name} IS '${details.table_comment.replace(/'/g, "''")}';`);
    }
    details.columns.forEach(c => {
      if (c.comment) {
        sql.push(`COMMENT ON COLUMN ${details.summary.schema}.${details.summary.table_name}.${c.name} IS '${c.comment.replace(/'/g, "''")}';`);
      }
    });
    return sql.length > 0 ? sql.join("\n\n") : "-- No comments";
  };

  const generateFunctions = () => {
    if (!details.functions || details.functions.length === 0) return "-- No functions";
    return details.functions.map(f => f.source).join("\n\n");
  };

  const getActiveCode = () => {
    switch (activeTab) {
      case "DDL": return generateCreateTable();
      case "INDEXES": return generateIndexes();
      case "CONSTRAINTS": return generateConstraints();
      case "TRIGGERS": return generateTriggers();
      case "POLICIES": return generatePolicies();
      case "COMMENTS": return generateComments();
      case "FUNCTIONS": return generateFunctions();
      default: return "";
    }
  };

  const tabs = [
    { id: "DDL", label: "DDL", active: true },
    { id: "INDEXES", label: "Indexes", active: details.indexes && details.indexes.length > 0 },
    { id: "CONSTRAINTS", label: "Constraints", active: details.constraints && details.constraints.length > 0 },
    { id: "TRIGGERS", label: "Triggers", active: details.triggers && details.triggers.length > 0 },
    { id: "POLICIES", label: "Policies", active: details.rls && details.rls.policies && details.rls.policies.length > 0 },
    { id: "COMMENTS", label: "Comments", active: details.table_comment || details.columns.some(c => c.comment) },
    { id: "FUNCTIONS", label: "Functions", active: details.functions && details.functions.length > 0 },
  ].filter(t => t.active);

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([getActiveCode()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${details.summary.table_name}_${activeTab.toLowerCase()}.sql`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // If activeTab is no longer valid, fallback to first tab
  if (!tabs.find(t => t.id === activeTab) && tabs.length > 0) {
    setActiveTab(tabs[0].id);
  }

  return (
    <div>
      <h3 className="text-[18px] font-semibold text-foreground mb-3 flex items-center gap-2">
        <CodeBlockIcon weight="fill" className="text-muted-foreground" /> SQL Definition
      </h3>
      <div className="bg-background border border-border/60 rounded-2xl shadow-sm overflow-hidden flex flex-col">
        <div className="flex border-b border-border/60 overflow-x-auto bg-muted/40 sticky top-0 z-10">
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                "px-5 py-3 text-[14px] font-semibold whitespace-nowrap transition-colors border-b-2",
                activeTab === tab.id 
                  ? "border-blue-500 text-blue-600 bg-background" 
                  : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/60"
              )}
            >
              {tab.label}
            </button>
          ))}
          <div className="flex-1"></div>
          <div className="flex items-center gap-2 px-2 sticky right-0 bg-muted/40 backdrop-blur-sm">
            <button 
              onClick={handleCopy}
              className="px-3 py-1.5 my-1 text-[13px] font-medium bg-background hover:bg-muted text-foreground rounded-md flex items-center gap-1.5 transition-colors border border-border/60 shadow-sm"
              title="Copy to clipboard"
            >
              {copied ? <CheckIcon className="text-emerald-500" /> : <CopyIcon />}
              {copied ? "Copied" : "Copy"}
            </button>
            <button 
              onClick={handleDownload}
              className="px-3 py-1.5 my-1 text-[13px] font-medium bg-background hover:bg-muted text-foreground rounded-md flex items-center gap-1.5 transition-colors border border-border/60 shadow-sm"
              title="Download SQL"
            >
              <DownloadIcon />
              Download
            </button>
          </div>
        </div>
        <div className="p-0 min-h-[300px] overflow-auto">
          <CodeMirror
            value={getActiveCode()}
            height="100%"
            theme={tokyoNight}
            extensions={[sql({ dialect: PostgreSQL, upperCaseKeywords: true })]}
            editable={false}
            style={{ fontSize: "14px", minHeight: "300px" }}
            className="h-full"
          />
        </div>
      </div>
    </div>
  );
}
